#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=None

cmake --build   build
cmake --install build

mkdir -p "$1/usr/lib/pkgconfig"
install "$1/usr/share/pkgconfig/eigen3.pc" "$1/usr/lib/pkgconfig/eigen3.pc"
